### ISSUE TITLE
Conflict with SwupHeadPlugin

### ISSUE THREAD

**Issue by delanfranchi** [swup/progress-plugin#1] opened 2020-11-05 20:08 UTC
Hi,

I think there is a conflict with SwupHeadPlugin.
The progress bar never reach the right of the page.

To fix the issue i changed : 

```javascript
	document.documentElement.insertBefore(this.progressElement, document.body);
```
into 

```javascript
	document.documentElement.prepend(this.progressElement, document.body);
```

But maybe you would think about another solution with better support.

Thanks

**Comment by daun** [comment] 2020-11-05 21:15
What's the exact problem you're trying to solve? Can you provide a reproducible test case or narrow it down to a browser vendor?

If I remember correctly, `node.prepend` will insert the progress element before `<html>` which doesn't make sense. The second argument here has no effect. Then again, `insertBefore` the body seems strange as well...

**Comment by delanfranchi** [comment] 2020-11-06 01:21
Here it is, the progress bar disapears before the end of the animation :
https://codepen.io/delanfranchi/project/editor/AoGGPO
(if there is a more convenient way to share issue, i would be pleased to know)

I thought the issue appeares because the progressbar is added beetween `</head>|<body>`
But i'm not sure now. :/

And you're right prepend doesn't seems to work like that... ( vanilla newbie , spotted)

**Comment by daun** [comment] 2020-11-06 12:17
I think the issue stems from the very long transition you use for your content containers. The progress bar disappears when the content is replaced, i.e. right between the out transition and the in transition. You could use the `transition` parameter of the plugin to set a similar duration which would lower the visual difference between the two transitions.


```js
new SwupProgressPlugin({ transition: 3000 })
```

You're right though that the bar never fully reaches 100%. This is because swup doesn't currently provide access to the underlying AJAX request to let us get an accurate reading of the progress. Instead, we're kind of faking it here to give some visual feedback that things are happening without being too accurate about it. This could certainly be optimized at some point.

**Comment by daun** [comment] 2020-11-06 12:19
I still don't quite understand how or why the code you suggested is fixing anything. I'll make a note to try it out in a few browsers to see if it has any side effects.

**Comment by delanfranchi** [comment] 2020-11-06 12:51
Forget about my suggestion, I made a mistake.
The code was wrong and as I said, I thought this was because of the position of the element, but it was wrong.

The very long transition was set to have the time to see it desapear in the middle.
If i comment `// new SwupHeadPlugin(),` it works well, despite the long transition.

**Comment by delanfranchi** [comment] 2020-11-06 14:05
Ok i found the real problem, after i forced a css transition to progress-bar.

It was not about the progress-bar, **but about the stylesheet** :
```javascript
installStylesheetElement() {
    document.head.insertBefore(this.stylesheetElement, document.head.firstChild);
}
```
The swup head plugin remove the `<style>` tag before css transition end.
So i add stylesheed to body and it works well, without writing extra css outside.

```javascript
installStylesheetElement() {
     document.body.prepend(this.stylesheetElement);
}
```

Maybe progress-bar and stylesheet could be both added in top of body ?
Here i changed insertBefore to prepend an remove progress-bar refer to the body, and it works.... this time >_> 


```javascript
export default class ProgressBar {
	className = 'progress-bar';
	animationDuration = 300; // ms
	minValue = 0.1;

	stylesheetElement = null;
	progressElement = null;

	hiding = false;
	trickleInterval = null;
	value = 0;
	visible = false;

	constructor({ className = null, animationDuration = null }) {
		if (className !== null) {
			this.className = className;
		}
		if (animationDuration !== null) {
			this.animationDuration = animationDuration;
		}

		this.stylesheetElement = this.createStylesheetElement();
		this.progressElement = this.createProgressElement();
	}

	get defaultCSS() {
		return `
    .${this.className} {
        position: fixed;
        display: block;
        top: 0;
        left: 0;
        height: 3px;
        background-color: black;
        z-index: 9999;
        transition:
          width ${this.animationDuration}ms ease-out,
          opacity ${this.animationDuration / 2}ms ${this.animationDuration / 2}ms ease-in;
        transform: translate3d(0, 0, 0);
      }
    `;
	}

	show() {
		if (!this.visible) {
			this.visible = true;
			this.installStylesheetElement();
			this.installProgressElement();
			this.startTrickling();
		}
	}

	hide() {
		if (this.visible && !this.hiding) {
			this.hiding = true;
			this.fadeProgressElement(() => {
				this.uninstallProgressElement();
				this.stopTrickling();
				this.visible = false;
				this.hiding = false;
			});
		}
	}

	setValue(value) {
		this.value = Math.max(this.minValue, value);
		this.refresh();
	}

	// Private

	installStylesheetElement() {
		document.body.prepend(this.stylesheetElement);
	}

	installProgressElement() {
		this.progressElement.style.width = '0';
		this.progressElement.style.opacity = '1';

		document.body.prepend(this.progressElement);
		this.refresh();
	}

	fadeProgressElement(callback) {
		console.log('fade')
		this.progressElement.style.opacity = '0';
		setTimeout(callback, this.animationDuration * 1.5);
	}

	uninstallProgressElement() {
		if (this.progressElement.parentNode === document.body) {
			document.body.removeChild(this.progressElement);
		}
	}

	startTrickling() {
		if (!this.trickleInterval) {
			this.trickleInterval = window.setInterval(this.trickle, this.animationDuration);
		}
	}

	stopTrickling() {
		window.clearInterval(this.trickleInterval);
		delete this.trickleInterval;
	}

	trickle = () => {
		const advance = (Math.random() * 3) / 100;
		this.setValue(this.value + advance);
	};

	refresh() {
		requestAnimationFrame(() => {
			this.progressElement.style.width = `${10 + this.value * 90}%`;
		});
	}

	createStylesheetElement() {
		const element = document.createElement('style');
		element.type = 'text/css';
		element.textContent = this.defaultCSS;
		return element;
	}

	createProgressElement() {
		const element = document.createElement('div');
		element.className = this.className;
		return element;
	}
}

```

**Comment by daun** [comment] 2020-11-06 16:31
Oh, great find, that sounds plausible. Some thoughts:

1. Style tags are semantically only valid in the `head`. Even though it's not very likely, it's possible that browsers will stop supporting style tags in the `body` at some point. I'm more comfortable leaving it in the head for now and instead focussing on number 2 below.
2. I'd argue this is an issue with the head plugin rather than the progressbar plugin. Currently, the head plugin removes all style tags and scripts that aren't present in the new page, which is why the progressbar styles are removed. I created [a pull request that solves this](https://github.com/swup/head-plugin/pull/11) by adding an option to keep all assets in the head on page change, however it hasn't yet been reviewed or integrated. If you can include swup from that branch, it would solve this particular problem.
3. In the meantime, we could add a note to the readme that those two plugins don't work well in combination.

**Comment by delanfranchi** [comment] 2020-11-06 17:58
I'm more uncomfortable about a `<div>` oustide the `<body>` than `<style>` inside it. 😅 But if it's not valid, you're right.
When i searched for a solution i found this issue : https://github.com/swup/head-plugin/issues/4

I think your pull request is necessary, other libraries could insert code in head.

Last, don't you think Constructible Stylesheets could be useful instead for creating a `<style>` tag ? 
I never use them, so i don't know where it's good or not, but maybe it can be useful. 

```javascript
createStylesheetElement() {
	const sheet = new CSSStyleSheet();
	sheet.replaceSync(this.defaultCSS);
	document.adoptedStyleSheets = [...document.adoptedStyleSheets, sheet];
}
```
and removing `installStylesheetElement()`

**Comment by daun** [comment] 2020-11-06 18:56
You're right that the div outside the body is just as wrong 🤡 The `ProgressBar` class however (which creates the style tag and inserts it) is a direct port of [the one Turbolinks uses](https://github.com/turbolinks/turbolinks/blob/866a29c861b0e0e0625a06189a49e29abd7a344a/src/progress_bar.ts#L60), which as a library is in use on millions of websites and I assume those decisions have been vetted by enough people to get it right.

Constructible Stylesheets would indeed be a nice workaround, but they're only supported in Chrome as far as I can tell. [Firefox doesn't have them](https://bugzilla.mozilla.org/show_bug.cgi?id=1520690), at least.

In the end, I feel like the issue here lies with the head plugin. Let's rather try and get that pull request approved.

**Comment by gmrchk** [comment] 2020-11-29 23:56
Hi, sorry it took a while! The Head plugin has been updated to v1.1.0 with @daun's suggestions. That should make it possible for the two plugins to existing together without any problems, at least with correct options.

I wouldn't worry about the style tag really unless some other option (like CSSStyleSheet) has some real advantages, which I'm not aware of. Correct me if I'm wrong, please. 
As for the `div` outside of `body`, I think it would be better to place it right at the top of `body`, but nowadays browser takes whatever you give it, so I guess it doesn't matter. 🤷‍♂️ 

Just thinking, maybe swup plugins should be adding some data attributes to its styles etc. that it's placing to the DOM, so we can later easily identify it? 🤔 
**Edit:** Seems like I've had this idea before. https://github.com/swup/theme/blob/247ce8a21235e08ec48bc16e704a53314705184d/src/index.js#L60

Anyway, I think we can close this now, but please reopen if I'm wrong.

**Closed as completed by gmrchk** 2020-11-29 23:56 UTC

**Comment by delanfranchi** [comment] 2020-12-01 07:34
Hi, and of course, thanks for the update.

About CSSStyleSheet, the bigger advantage was that is was not deleted by Swup head. :)
CSS tag still have a better support but I'd like the idea that css created by js was not in the dom. It could be added or removed by the plugin itself.

As you said, the update still need attributes on swup plugins tags.
Because I don't know how to make progress bar css persistent without hack.  Or I miss something :/

**Comment by daun** [comment] 2020-12-01 09:21
You can use the new `persistAssets` options of the head plugin and the stylesheet will persist. [See the docs](https://github.com/swup/head-plugin#persistassets).

**Comment by delanfranchi** [comment] 2020-12-03 12:53
I already read the docs. :)

But I can't use "persistAssets" in my project.
I'm working on adding Swup on a drupal9. But Drupal add js and css according to context (page or module loaded).

I think "persistAssets" could create some unwanted effects. It will be great if progress Css tag have a specific attribute.
If you think it's a too specific need, I will add css fix to my project, and it will be still good.

thanks again.
